### ISSUE TITLE
The performance test can not be running under Firefox properly

### ISSUE THREAD

**Issue by lygstate** [google/lovefield#106]
When I running performance test by
`gulp test --target=perf "--browser=firefox"`

It's failed with the following result:
```
[00:28:09] Using gulpfile C:\CI-Cor\ks\lovefield\gulpfile.js
[00:28:09] Starting 'debug'...
Generating 1 HTML test files ...
Found 0 test files with existing HTML...

Test files generated. Starting server @C:\Users\lygstate\AppData\Local\Temp\1445876889760.207 ...

[00:28:09] Finished 'debug' after 78 ms
[00:28:09] Starting 'test'...
[ 'firefox' ]
Found 1 tests. Running...
[00:28:11] Server started http://localhost:8000
[00:28:11] LiveReload started on port 35729

C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\goog\async\nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                      ^
UnexpectedAlertOpenError: Unexpected modal dialog (text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the scr
script continue.

Script: http://localhost:8000/lib/cache/journal.js:191)
    at bot.Error [as constructor] (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\atoms\error.js:108:18)
    at Function.childCtor.base (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\goog\base.js:2254:45)
    at new webdriver.UnhandledAlertError (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:2436:33)
    at C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:384:15
    at promise.ControlFlow.runInFrame_ (C:/CI-Cor/ks/lovefield/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at goog.defineClass.notify (C:/CI-Cor/ks/lovefield/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at promise.Promise.notify_ (C:/CI-Cor/ks/lovefield/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (C:/CI-Cor/ks/lovefield/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)
From: Task: WebDriver.executeScript()
    at webdriver.WebDriver.schedule (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:362:15)
    at webdriver.WebDriver.executeScript (C:\CI-Cor\ks\lovefield\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:533:15)
    at null.<anonymous> (C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:172:25)
    at C:\CI-Cor\ks\lovefield\tools\jsunit_test_runner.js:181:7
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by arthurhsu** [comment]
This is because Firefox is asking for permission to persist data on disk. Please run gulp debug and run the perf test manually, set the permission, then you can test it with automated mode.
