### ISSUE TITLE
TypeError: c is not a function

### ISSUE THREAD

**Issue by desvandev** [google/lovefield#191]
Hello, I'm building a test app using Lovefield.
I've successfully created a database and some tables, but when I try to insert some data to one table I got this error:

```javascript
TypeError: c is not a function
    at Object.eval [as admins.pkAdmins] (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:269:494)
    at d.Yk.d.nb (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:270:294)
    at Xc (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:69:224)
    at Rc.eval (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:69:84)
    at Array.forEach (native)
    at Wc (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:69:60)
    at wd (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:78:196)
    at ud.m.Ab (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:78:92)
    at rj.ca (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:227:382)
    at rj.eval (eval at <anonymous> (js/admin_crud.js:109:1), <anonymous>:186:1091)
```

WO.wolf is an object with a custom class with some helper functions for lovefield
```javascript
let rows = r.data.items.map((obj) => {
        obj.uuid = woh.uuid();
        return WO.wolf.t[WO.section.table].createRow(obj);
    });
    console.log("rows", rows);  /* <-- rows created are fine */
    return WO.wolf.db.insert()
        .into(WO.wolf.t[WO.section.table])
        .values(rows).exec();  /* <-- here's the error  */
```

The thing is, I've tried to use the non minified version but I get some es6 errors. So the line where the error come from is this one:

```javascript
var e = function(a) {
            var b = this.K.get(a.getName())
              , c = this.Qd.Ze.get(b) || null;
            return function(b) {
                return c(b[a.getName()]) /* <-- here! */
            }
        }
```

I don't know what to do, I've follow every step  :thinking:

**Comment by desvandev** [comment]
Just in case my WO.wolf thing was misleading, here is a little test which give me the same error.

```javascript
var sb = lf.schema.create('wodbtest', 1);
sb.createTable('admins')
    .addColumn('id', lf.type.INTEGER)
    .addColumn('name', lf.type.STRING)
    .addPrimaryKey(['id']);

sb.connect({storeType: lf.schema.DataStoreType.INDEXED_DB}).then((db) => {
    var table = db.getSchema().table('admins');
    var row = table.createRow({
        id:1,
        name:"Jhon Wolf"
    });
    try {
        db.insert().into(table).values([row]).exec()
            .then((result) => console.log(result));
    } catch(err) {
        console.log(err);
    }
});
```

**Comment by desvandev** [comment]
Now this is working:
```javascript
var sb = lf.schema.create('wodbtest', 1);
sb.createTable('admins')
    .addColumn('name', lf.type.STRING);

sb.connect({storeType: lf.schema.DataStoreType.INDEXED_DB}).then((db) => {
    var table = db.getSchema().table('admins');
    var row = table.createRow({
        name:"Jhon Wolf"
    });
    try {
        return db.insert().into(table).values([row]).exec();
    } catch(err) {
        console.log(err);
    }
}).then((r) => {
    console.log('it works!', r);
});
```
Why I can't set as PK one of my columns?

**Comment by arthurhsu** [comment]
You have misspelling in your code: lf.Type, not lf.type.

**Comment by desvandev** [comment]
Sorry Arthur, but I don't have a typo!

**Comment by arthurhsu** [comment]
lf.Type is an enum, which will be converted into a special value. If you did not type exactly as-is, the error you're seeing will be there.
