### ISSUE TITLE
can't authenticate with firebase

### ISSUE THREAD

**Issue by vbresults** [google/lovefield#239]
```
TypeError: this.Df.child is not a function
    at Ve.m.Ea (/<path>/node_modules/lovefield/dist/lovefield.min.js:111:33)
    at yk (/<path>/node_modules/lovefield/dist/lovefield.min.js:243:843)
    at W.Ea (/<path>/node_modules/lovefield/dist/lovefield.min.js:251:237)
    at Zk.connect (/<path>/node_modules/lovefield/dist/lovefield.min.js:273:192)
    at default_1.<anonymous> (/<path>/node_modules/<snip>/adapter/lovefield.js:68:57)
    at next (native)
    at fulfilled (/<path>/node_modules/<snip>/adapter/lovefield.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

```
		const app = firebase.initializeApp(config.options || {});

		let auth;

		if (config.user) {
			auth = await app.auth().signInWithEmailAndPassword(config.user.email_address, config.user.password);
		} else {
			auth = await app.auth().signInAnonymously();
		}

		return lf.schema.create(config.database, 1).connect({
			storeType: lf.schema.DataStoreType.FIREBASE,
			firebase: auth
		});
```

**Comment by arthurhsu** [comment]
Can you use lovefield.js instead? It's hard for human to decode source map instead of machines.

**Comment by vbresults** [comment]
lovefield@^2.1.12
```
TypeError: this.app_.child is not a function
    at lf.backstore.Firebase.init (/<snip>/node_modules/lovefield/dist/lovefield.js:6149:24)
    at Object.lf.base.init (/<snip>/node_modules/lovefield/dist/lovefield.js:11510:20)
    at lf.proc.Database.init (/<snip>/node_modules/lovefield/dist/lovefield.js:11808:18)
    at lf.schema.Builder.connect (/<snip>/node_modules/lovefield/dist/lovefield.js:12452:19)
    at default_1.<anonymous> (/<snip>/node_modules/<snip>/data/source/database/adapter/lovefield.js:68:57)
    at next (native)
    at fulfilled (/<snip>/node_modules/<snip>/data/source/database/adapter/lovefield.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by freshp86** [comment]
Looking at the Firebase tests at https://github.com/google/lovefield/blob/741cef2e35ccdaa0b27b03edfed883e7e78c0f18/tests/backstore/firebase_test.js#L72, you are supposed to pass the result of `new Firebase` to the `connect` function. I don't know what `firebase.initializeApp` does in your snippet, but it seems to not be returning the right thing.

**Comment by vbresults** [comment]
There is no `Firebase` class exposed by `firebase@^5.0.4` from npm.  Am I supposed to be using another package for node?

**Comment by freshp86** [comment]
Per the closure compiler Firebase externs definitions [here](https://github.com/google/lovefield/blob/741cef2e35ccdaa0b27b03edfed883e7e78c0f18/builddef/firebase_externs.js), the expected class is [this one](https://www.firebase.com/docs/web/api/firebase/constructor.html).

So unless the Node based API matches that, I don't think it is going to work. Lovefield would have to be modified in some way to accommodate two different APIs.

**Comment by freshp86** [comment]
Looking more at the new docs, it seems that the Firebase API that Lovefield currently understands is deprecated, and the new one is at https://firebase.google.com/docs/reference/js/firebase.app.App.

**Comment by vbresults** [comment]
I think the new API is Cloud Firestore; I was hoping at least to be able to use the legacy Realtime Database as a replacement for MySQL in node with lovefield 😞

**Comment by vbresults** [comment]
@arthurhsu What is the chance of a modern node-compatible implementation coming?

**Comment by vbresults** [comment]
@freshp86

**Comment by freshp86** [comment]
@vbresults Realistically the chances are low, since both myself and @arthurhsu are not working 100% on Lovefield anymore, but we do maintain it and fix critical bugs.

Having said that, I do think is worth either re-opening this issue, or filing a new one as a feature request, in case someone else decides to send a PR, or in case our time commitment changes in the future.

**Comment by arthurhsu** [comment]
I would not count on replacing MySQL node implementation with Lovefield + Firebase. Cloud based backstore has a lot of limitations and the I/O speed can be daunting. You might get better luck to implement customized SQLite that can sync its pages across the cloud, which get you the speed and power. The only problem is that it's just hard.
